dependencies:
  - pip:
    - pip    
    - numpy 
    - pandas 
    - scipy
    - plotly 
    - kaleido
    - jsonschema
    - pronto
    - requests
    - git+https://github.com/MS-Quality-hub/mzqc-pylib.git@v1.0.0#egg=mzqc-pylib
